### ISSUE TITLE
Loading spinner/gif

### ISSUE THREAD

**Issue by ninabreznik** [ethereum-play/smartcontract.codes#14]
Add loading spinner:

- [ ] while waiting for database to load initially
- [ ] while compiling
- [ ] while searching for matches
- [ ] add the search tips

**Comment by ninabreznik** [comment]
- [IBM SEARCH](https://www.ibm.com/search?lang=en&cc=us)

**Comment by serapath** [comment]
clsoe and transition to https://github.com/playproject-io/smartcontract.codes/issues/6
