### ISSUE TITLE
Collection card cover

### ISSUE THREAD

**Issue by ninabreznik** [ethereum-play/smartcontract.codes#16]
- [ ] remove click event
- [ ] add `connect` icon and `copy` icon next to contract address (if many deployed contracts with same address, make dropdown)
  - when connect icon is clicked, it opens selected deployed instance in full page smartcontract UI (at address)
- if copy icon is clicked, it copies the selected address to the clipboard

**Comment by serapath** [comment]
close and transition to https://github.com/playproject-io/smartcontract.codes/issues/8
